### ISSUE TITLE
请问可以用api调用吗

### ISSUE THREAD

**Issue by aqpmzngldh** [ZillaRU/OpenVoice-tpu#1]

**Comment by ZillaRU** [comment]
什么功能的 API 调用呢？TTS 还是音色克隆？TTS 的话可以看我主页另一个项目[EmotiVoice-tpu](https://github.com/ZillaRU/EmotiVoice-TPU)。

**Comment by aqpmzngldh** [comment]
> 什么功能的 API 调用呢？TTS 还是音色克隆？TTS 的话可以看我主页另一个项目[EmotiVoice-tpu](https://github.com/ZillaRU/EmotiVoice-TPU)。

 OpenAI 的 TTS 音色太少了，不是我想要的，我想要自己可以训练出的模型并像OpenAI 的 TTS 那样通过api调用，比如沸羊羊声音或者其他人的声音

**Comment by ZillaRU** [comment]
可以看看emotivoice和openvoice原项目，都支持自定义音色的。其中openvoice直接是推理阶段克隆。我的仓库基本只关注这些方案的最基本pipeline适配到国产芯片这部分。

**Comment by aqpmzngldh** [comment]
> 可以看看emotivoice和openvoice原项目，都支持自定义音色的。其中openvoice直接是推理阶段克隆。我的仓库基本只关注这些方案的最基本pipeline适配到国产芯片这部分。

好的，谢谢你
